"""
conversation.py — ORM models for conversations and messages

Two tables:
  - conversations: one row per chat session (has a title, linked to a user)
  - messages:      one row per message (user or AI), linked to a conversation

Why separate tables instead of storing messages in a JSON column?
  - Easier to query: "show me all conversations from this week"
  - Easier to paginate: fetch messages 20 at a time
  - Cleaner for future features like search, analytics, message editing

The `thread_id` on Conversation maps directly to LangGraph's thread concept.
LangGraph stores its own state keyed by thread_id — having the same ID in both
systems keeps things consistent.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Conversation(Base):
    __tablename__ = "conversations"

    id: Mapped[str] = mapped_column(String,
                                    primary_key=True,
                                    default=lambda: str(uuid.uuid4()))
    # thread_id = the same ID passed to LangGraph's checkpointer for memory continuity
    thread_id: Mapped[str] = mapped_column(
        String,
        unique=True,
        nullable=False,
        index=True,
        default=lambda: str(uuid.uuid4()),
    )

    user_id: Mapped[str] = mapped_column(String,
                                         ForeignKey("users.id",
                                                    ondelete="CASCADE"),
                                         nullable=False,
                                         index=True)

    # Auto-generated title (we'll set this from the first user message)
    title: Mapped[str] = mapped_column(String(255), default="New conversation")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    user: Mapped["User"] = relationship(
        "User", back_populates="conversations")  # noqa: F821
    messages: Mapped[list["Message"]] = relationship(
        "Message",
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="Message.created_at",
    )

    def __repr__(self) -> str:
        return f"<Conversation id={self.id} user_id={self.user_id}>"


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[str] = mapped_column(String,
                                    primary_key=True,
                                    default=lambda: str(uuid.uuid4()))
    conversation_id: Mapped[str] = mapped_column(String,
                                                 ForeignKey(
                                                     "conversations.id",
                                                     ondelete="CASCADE"),
                                                 nullable=False,
                                                 index=True)

    # "user" = typed by the human; "assistant" = generated by Gemini
    # Using the same naming convention as LangChain/OpenAI (easier to map later)
    role: Mapped[str] = mapped_column(String(20),
                                      nullable=False)  # "user" | "assistant"

    content: Mapped[str] = mapped_column(Text, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    conversation: Mapped["Conversation"] = relationship(
        "Conversation", back_populates="messages")

    def __repr__(self) -> str:
        return f"<Message id={self.id} role={self.role}>"
